version: "3.2"
services:
  redis_srv:
    image: redis:6.2.6
    container_name: ml_redis
  
  model_srv:
    image: ml_service
    container_name: ml_service
    build:
      context: ./model
      target: build
    depends_on:
      - redis_srv
    volumes:
      - ./uploads:/src/uploads
    ports:
      - "6379:6379"
      
